# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('genre2', models.CharField(max_length=20)),
                ('date', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('cate1', models.CharField(max_length=20)),
                ('url', models.TextField()),
                ('img', models.TextField()),
                ('price', models.IntegerField()),
                ('org_price', models.IntegerField()),
            ],
        ),
    ]
